# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d050f0873fb9d9ce5c3f0c1edc46a04481c8350db946cb6478e80d1c685d56d0eaf2f380d86719c5488f7eb27823fe457f72b2f8ad6173c23255e225c2cdc602

test:
  secret_key_base: cc3b39dda9b383d9b9fec405485c3457d0f445049eb5f38df52c7d2751e6e5fef6b71f68a3aa01e13baafb96300de9aa39ccea565ce2797797f79cc362760173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
